

%%% print_reply(Reply)
%%%
%%% Reply ==> reply generated by reply predicate
%%%           that is to be printed to the standard output.

print_reply(error(ErrorType)) :-
     write('Error: "'), write(ErrorType), write('."'), nl.

print_reply(asserted(Assertion)) :-
     write('Asserted "'), write(Assertion), write('."'), nl.
%%% added
print_reply(retract(Retraction)):-
    write('Retracted"'), write(Retraction), write('."'),nl.
%%%
print_reply(answer(Answers)) :- print_answers(Answers).

